presentations/2023-03-23_collaborative-working/index.qmd

I would LOVE some comments about this talk I have prepared for the R&P team all about- working in collaboration and seeking feedback on outputs and pull requests :wink: 
I may tweak it again but this is a near final version

Commit collaborative working talk

---

_quarto.yml

mergers the changes from a couple of branches that got lost during #38 and #40

fixes the _quarto.yml file

---

style/git_and_github.qmd

GitHub workflw

---

style/git_and_github.qmd

Reverts The-Strategy-Unit/data_science#61

Revert "GitHub workflw"

---

style/git_and_github.qmd

Following up from slack discussion. Happy for feedback and comments/changes

adds PR workflow to the guide

---

_quarto.yml
newpagelink.lua

opens external links in new tabs

---

_quarto.yml

adds a default empty sidebar

---

presentations/2023-10-09_nhs-r_conf_sd_in_health_social_care/index.qmd

maybe I shouldn't have closed that earlier pull request?

re-write of functions

---

style/git_and_github.qmd
style/style_guide.qmd

closes #76, closes #39, closes #31, closes #12

assorted style updates

---

blogs/posts/2024-01-10-advent-of-code-and-test-driven-development.qmd

added blogpost

---

about.qmd
index.qmd

updated about and index pages

---

presentations/index.qmd

Added sort to table, styling changes, changed column widths

---

renv.lock
renv/activate.R

updates renv to 1.0.5, updates all other packages at same time

updates renv

---

about.qmd

Add Rhian to team list

---

.all-contributorsr.json
README.md

I messed up the placing of the contributors table. 
This fixes

Fix formatting of README

---

blogs/posts/2024-05-13_one-year-coffee-code.qmd

Short post on the coffee & coding results

Initial coffee & code post

---

blogs/posts/2024-05-13_one-year-coffee-code.qmd

Should have proofread it when I wasn't tired 🤦🏻

Fix typos in c&c blog

---

presentations/2024-05-16_store-data-safely/index.qmd
presentations/index.qmd

handles case where there are multiple authors listed in a single string, or as a list of authors

resolves an issue where multiple authors don't work

---

presentations/index.qmd

stops presentations index from freezing

---

blogs/posts/2024-05-22-storing-data-safely/azure_python.ipynb
blogs/posts/2024-05-22-storing-data-safely/index.qmd

added code-rich blog to accompany storing data safely presentation

---

about.qmd

Fix broken link

---

blogs/index.qmd

hides .ipynb file containing code for blogpost from blog list

---

blogs/posts/2024-08-08-map-and-nest/index.qmd

:rocket: Timetravel to 2024

---

presentations/2024-10-10_what-is-ai-yiwen/index.qmd

Slides for "basic ML" part of What is AI talk 

---

presentations/2024-10-10_what-is-ai-yiwen/index.qmd

incorporates Sheilas suggestions

---

README.md

Closes #239 
Does it make sense??

renv documentation added

---

presentations/2024-11-21_agile_project_management/index.qmd

244 nhs rpysoc talk

---

_quarto.yml
style/team.qmd

Fixes #259
Have added some basic things about the way we work as a team.
All suggestions welcome.
Screen grab of local rendered version

:memo: Add onboarding information

---

blogs/posts/2024-12-04-gha-branch-preview/index.qmd

Great blog! Ruined by this typo.

Correct 'Qaurto' typo

---

style/team.qmd

Following the discussion on Thursday with Chris & YiWen

📝 Update stand-up documentation

---

presentations/2025-02-27_word-not-quarto/index.qmd

Related to #272. Add presentation skeleton to show people in the session. May add some (suitably blurred) screenshots after the session.

Add mail merge C&C presentation

---

blogs/posts/2024-11-29-mapping-my-r-learning/index.qmd

🐛 Fix URLs in footnotes

---

_quarto.yml
blogs/posts/2024-05-22_storing-data-safely/index.qmd

see https://quarto.org/docs/projects/code-execution.html#freeze - when set to true, files are never re-rendered. auto should re-render when files are changed

change freeze from true to auto

---

style/style_guide.qmd

Namespaces dplyr functions in example B of style guide as recommended in code style section of style guide

Update style_guide.qmd example

---

style/data_storage.qmd
style/style_guide.qmd

Add date format and data storage info

---

style/style_guide.qmd

Close #310.
* Add bullet re Quarto editor mode and link to guidance.
* Bonus: add note re successive mutate calls.

Add note to prefer source editor

---

about.qmd
renv.lock

PR for issue #305 . Given Rtools seems to be a Windows-only package, setting up R and Quarto on Linux can be _slightly_ painful :sob: 
If people are happy with the website as it is, that's fine. Otherwise, I'm happy to look into more lightweight / responsive alternatives to leverage e.g. Jekyll, Hugo and so on.
For reproducibility:  
```zsh
$ sudo echo "deb http://cloud.r-project.org/bin/linux/debian bookworm-cran40/" >> /etc/apt/sources.list
$ sudo apt update
$ sudo apt install r-base r-base-dev curl -y # Install the latest R
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash # Install Node Version Manager
$ source ~/.zshrc # Reload shell. Replace .zshrc with .bashrc if you use Bash
$ nvm install 22 # Install Node v22 (LTS)
```
- Install …

add: me to team page

---

about.qmd

Added Ash to about page
